# run: conda env create --file environment.yml
# optionally, change channel name with -n {ds}
name: ds
dependencies:
  - python
  - numpy
  - opencv
  - paramiko
  - psycopg
  - tqdm
  - nb_conda
  - jupyterlab
  - pytest
  - flake8
  - conda-forge::cryptography
channels:
  - conda-forge
  - defaults
